language: scala
scala:
- 2.11.7
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - shaoxinjiang@gmail.com
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - mysql -u root < scripts/db_clean.sql
  - mysql -u root < scripts/db_init.sql
  - mysql -u scim_test -p1e0OZH5f9asCJ0Anj11ia0Wmy scim_test < scripts/db_schema.sql
  - mysql -u scim_test -p1e0OZH5f9asCJ0Anj11ia0Wmy scim_test -e 'show tables;'