version: '2'
services:
  web:
    build: .
    ports:
      - "8000:9000"
    links:
      - db
    volumes:
      - .:/code
    env_file:
      - .env
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: scim_rest
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: scim_test
      MYSQL_PASSWORD: 1e0OZH5f9asCJ0Anj11ia0Wmy