web:
  build: .
  ports:
    - 5000:80
  environment:
    DEBUG: 'true'
    JAWSDB_URL: "mysql://p4mt47a7xqt1cm7o:eajsoe048n7kbxpe@jw0ch9vofhcajqg7.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/kkye4k8grk0iedlz"